### ISSUE TITLE
Error in .data$y : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by RobertMyles** [kosukeimai/emIRT#3]
Hi, 

Every time I try to run the `hierIRT()` function, I get the error:

    Error in .data$y : $ operator is invalid for atomic vectors

`y` in this case is a numeric matrix. A simple example:

    y <- matrix(rbinom(50*60, 1, 0.5), 50, 60)
    hI <- hierIRT(.data = y)

    > hI <- hierIRT(.data = y)

    ==================== 
    hierIRT: approximate Bayesian inference for roll call data

    Error in .data$y : $ operator is invalid for atomic vectors

Thanks.

**Comment by jameslo989** [comment]
Hi Robert,

You’ll need to specify both starts and priors for the hierIRT() model as well.  In the example it’s dwnom$cur and dwnom$priors, and it’s documented in ?hierIRT()

James

On Nov 16, 2016, at 2:34 PM, Robert Myles McDonnell <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

Every time I try to run the hierIRT() function, I get the error:

Error in .data$y : $ operator is invalid for atomic vectors

y in this case is a numeric matrix. A simple example:

y <- matrix(rbinom(50*60, 1, 0.5), 50, 60)
hI <- hierIRT(.data = y)

> hI <- hierIRT(.data = y)

# 

hierIRT: approximate Bayesian inference for roll call data

Error in .data$y : $ operator is invalid for atomic vectors

Thanks.

**Comment by RobertMyles** [comment]
Ah, thank you, James. I didn't realise the other arguments were necessary, my mistake.
