### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by kosukeimai** [kosukeimai/emIRT#4]
A note from a user:

I was looking through the documentation and I think there may be some "cut and paste' errors. for example in the description of the hierarchical model hierIRT it says there can be only two categories but the data description says:

matrix of numeric values containing the data to be scaled. Respondents are assumed to be on rows, and items assumed to be on columns, so the matrix is assumed to be of dimension (N x J). For each item, only 3 ordered category responses are accepted, and the only allowable responses are ‘1’, ‘2’, and ‘3’, with ‘0’ as a missing data record. If data of more than 3 categories are to be rescaled, they should be collapsed into 3 categories and recoded accordingly before proceeding. 

I would love it to be 3 for an application I am thinking of but I assume that this is inaccurate. There are some similar issues elsewhere (e.g. "ordIRT estimates an dynamic IRT model with two response categories per item") and the description for the data there similarly talks about three ordered categories (again, for my application a dynordIRT would be great).

**Comment by jameslo989** [comment]
Resolved, on CRAN now.
