### ISSUE TITLE
emIRT installation

### ISSUE THREAD

**Issue by mgoplerud** [kosukeimai/emIRT#8]
Hello!

I am flagging two related issues. 

First, `emIRT` was removed from CRAN on 1/28/2022. 

Second, when my students and I tried to install it using an old version, i.e. `remotes::install_version('emIRT')`, the installation failed with errors about `PI` not being defined. This error occured on R 4.03 and R 4.1.2. I tried to install from the GitHub (again using `remotes`) and had some issues as well.

However, when I use  `devtools::install_version("kosukeimai/emIRT")`, we seemed to be able to succesfully install the package across different versions of R (3.6.3, 4.0.3 and 4.12).  

If useful, I can try to uninstall and reinstall to get the exact error message. Just let me know!

**Comment by kosukeimai** [comment]
Thanks @mgoplerud !  We will try to put this back up on CRAN asap!

**Comment by kosukeimai** [comment]
@mgoplerud Thanks for pointing this out. We are back at CRAN!
